load("@hash_frx_pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "blake3",
    srcs = [
        "__init__.py",
        "blake3.py",
        "compress.py",
    ],
    visibility = ["//visibility:public"],
    deps = [requirement("frx")],
)
