load("@hash_frx_pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "lane",
    srcs = [
        "__init__.py",
        "lane.py",
    ],
    deps = [
        requirement("frx"),
        requirement("numpy"),
    ],
)

py_library(
    name = "params",
    srcs = [
        "__init__.py",
        "params.py",
    ],
    deps = [":lane"],
)

py_library(
    name = "keccak",
    srcs = [
        "__init__.py",
        "permutation.py",
    ],
    deps = [
        ":lane",
        ":params",
        "//hash_frx:permutation",
        requirement("frx"),
        requirement("numpy"),
    ],
)
