load("@hash_frx_pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "keccak",
    srcs = [
        "__init__.py",
        "byte_hashes.py",
        "lane.py",
        "params.py",
        "permutation.py",
        "sponge.py",
        "streaming.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hash_frx:byte_hash",
        "//hash_frx:fusion",
        "//hash_frx:permutation",
        "//hash_frx:word",
        requirement("frx"),
        requirement("numpy"),
    ],
)
