# Copyright 2026 The hash-frx Authors. SPDX-License-Identifier: Apache-2.0
"""Named duplex conventions — which released implementation a sponge reproduces.

[`duplex_sponge.py`](../duplex_sponge.py) owns the *axes* (`RateLanes`,
`SpillPermute`, `SwitchPermute`) because they are properties of that
construction. This module
owns the *members*, because a convention is a claim about an external codebase —
"these axis settings are what ark-sponge 0.3 does" — and a claim about the
outside world is an adapter's business. The same split
[`block_size.py`](block_size.py) makes: the seam does not carry a block size,
and the table of which family has which is here.

**The name is the whole point.** A caller reaching for byte-compatibility knows
which implementation it has to match, not which combination of quirks that
implies; `ARK_0_3` answers the question they actually have. A boolean called
something like `legacy_spill` would not, which is why #156 asks for members named
by the thing they reproduce and axes named by mechanism.

    sponge = DuplexSponge(perm, rate=2, convention=ARK_0_3)

**Neither member is this construction's default.** `DEFAULT_CONVENTION` is
leading-rate (0.3's layout) with the corrected always-permute squeeze (0.5's
behaviour) and a permute on either direction switch (0.3 again), so it matches
neither release — which is why both members set all three axes rather than
"the default plus one quirk".

**The third axis was found by the differential, not by reading the diff.** 0.5's
`absorb` quietly dropped the `permute()` its 0.3 counterpart ran when squeezing
gave way to absorbing. Nothing in the release discussion mentions it, and no
script that absorbs and then only squeezes can see it; it surfaced because the
reference set carries one that turns back around.

**`ARK_0_3` reproduces a bug on purpose**, and that is only worth shipping
because it is pinned against the real thing: `adapter/testing/duplex_test.py`
holds both members to vectors generated by running the two crates themselves
(`adapter/testing/reference/arkvec/`). A convention row that merely self-agrees
would publish a compatibility claim nobody checked, which is worse than shipping
no row at all.

**Only two conventions ship here, and the other two named in #231 cannot.**
Plonky3's duplex absorbs by overwrite and squeezes high→low, which is the
`DuplexTranscript` convention that `duplex_sponge.py` keeps as a deliberately
separate construction — and one this package does not ship. A Keccak duplex
absorbs by XOR over an integer dtype, which `DuplexSponge.__init__` rejects with
a `TypeError` by design. Neither is a convention *of* this construction, so
neither has anything here to parameterize.
"""

from __future__ import annotations

from hash_frx.duplex_sponge import (
    DuplexConvention,
    RateLanes,
    SpillPermute,
    SwitchPermute,
)

ARK_0_3 = DuplexConvention(
    rate_lanes=RateLanes.LEADING,
    spill_permute=SpillPermute.SKIP_WHEN_REQUEST_EQUALS_RATE,
    switch_permute=SwitchPermute.BOTH_DIRECTIONS,
)
"""ark-sponge 0.3 (`arkworks-rs/sponge`, tag `v0.3.0`).

Rate leading — `squeeze_internal` reads `state[rate_start_index..]` — and the
spill permute skipped when the outstanding request equals the rate, which
re-emits already-squeezed lanes. That skip is a **bug**, fixed in 0.5; it ships
as a named member so a consumer that has to interoperate with 0.3 can, and it is
pinned by a differential case that fails against `ARK_0_5`.

0.3 hardcodes width 3 / rate 2 / capacity 1. Nothing here does — the convention
is the schedule, not the shape — but reference vectors for it necessarily use
those.
"""

ARK_0_5 = DuplexConvention(
    rate_lanes=RateLanes.TRAILING,
    spill_permute=SpillPermute.ALWAYS,
    switch_permute=SwitchPermute.ABSORB_TO_SQUEEZE_ONLY,
)
"""ark-crypto-primitives 0.5 (`sponge` feature), the release 0.3 became.

Rate trailing — every access is `state[capacity + ...]`, in absorb and squeeze
alike — and the spill permute made unconditional
(`if !output_remaining.is_empty()`, evaluated after the output slice advances).

Its `absorb` also stopped permuting on a squeeze-to-absorb switch, so absorbed
material lands on rate lanes a squeeze has already published.

Two of these three are not the bug fix, and not what a reader looking for the
0.3-to-0.5 change would find: the rate move changes every output of every
script, and the switch change is invisible until a script turns back around.
"""
