[package]
name = "arkvec"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-sponge-03 = { package = "ark-sponge", git = "https://github.com/arkworks-rs/sponge", tag = "v0.3.0" }
ark-ff-03 = { package = "ark-ff", version = "0.3" }
ark-bn254-03 = { package = "ark-bn254", version = "0.3" }

ark-cp-05 = { package = "ark-crypto-primitives", version = "0.5", features = ["sponge"] }
ark-ff-05 = { package = "ark-ff", version = "0.5" }
ark-bn254-05 = { package = "ark-bn254", version = "0.5" }
