# Copyright 2026 The hash-frx Authors. SPDX-License-Identifier: Apache-2.0
"""The named duplex conventions, held to the crates they name.

A convention row's entire content is "this reproduces that implementation", so a
test that only checks self-consistency proves nothing at all — it would publish
a compatibility claim nobody checked. The oracle here is therefore
`reference/ark_duplex_vectors.json`, generated by **running ark-sponge 0.3 and
ark-crypto-primitives 0.5 themselves** (that directory's README carries the
configuration and how to regenerate).

The reference config uses `partial_rounds = 0` deliberately, which makes the
permutation provably identical across both releases and this package — so a
difference in output is attributable to the sponge schedule and nothing else.
That the Poseidon *permutation* is right is `poseidon/testing/poseidon_test.py`'s
job, and holding it here too would fuse two independent questions into one
failure.

`ARK_0_3` reproduces a **bug**, so the case that matters most is the one where
it disagrees with `ARK_0_5` — pinned below as its own test rather than left to
the sweep, since a sweep that silently stopped exercising it would still pass.
"""

from __future__ import annotations

import json
import pathlib

import frx.numpy as fnp
import numpy as np
from absl.testing import absltest, parameterized
from zk_dtypes import bn254_sf_mont as F

from hash_frx.adapter.duplex import ARK_0_3, ARK_0_5
from hash_frx.duplex_sponge import (
    DEFAULT_CONVENTION,
    DuplexConvention,
    DuplexSponge,
    RateLanes,
    SpillPermute,
    SwitchPermute,
)
from hash_frx.poseidon.params import PoseidonParams
from hash_frx.poseidon.poseidon import Poseidon

_VECTORS = json.loads(
    (
        pathlib.Path(__file__).parent / "reference" / "ark_duplex_vectors.json"
    ).read_text()
)


def _to_field(canon: object) -> object:
    """Canonical ints -> field array. The dtype cast Montgomery-encodes, which
    is why the vector file's plain integers cannot be handed over as int64."""
    return fnp.asarray(np.asarray(canon, dtype=np.int64).astype(F))


def _to_canon(arr: object) -> list[int]:
    """Field array -> canonical ints (the object cast Montgomery-decodes, and
    needs no frx x64)."""
    return [int(v) for v in np.asarray(np.asarray(arr).astype(object), dtype=object)]


def _permutation() -> Poseidon:
    """The reference config's Poseidon, built from the vector file rather than
    from literals here — so the two cannot drift apart silently."""
    return Poseidon(
        PoseidonParams(
            width=_VECTORS["width"],
            dtype=F,
            alpha=_VECTORS["alpha"],
            full_rounds=_VECTORS["full_rounds"],
            partial_rounds=_VECTORS["partial_rounds"],
            mds=_to_field(_VECTORS["mds"]),
            round_constants=_to_field(_VECTORS["round_constants"]),
        )
    )


def _expected(values: list[str]) -> list[int]:
    """The vector file's canonical little-endian hex, as ints."""
    return [int.from_bytes(bytes.fromhex(v), "little") for v in values]


def _run(convention: DuplexConvention, steps: list[list]) -> list[int]:
    """Replay one absorb/squeeze script and return the squeezed elements.

    The absorbed values are `1, 2, 3, ...` in order across the whole script,
    which is what the generator feeds both crates.
    """
    sponge = DuplexSponge(_permutation(), rate=_VECTORS["rate"], convention=convention)
    out: list[int] = []
    nxt = 1
    for kind, count in steps:
        if kind == "absorb":
            elems = _to_field(list(range(nxt, nxt + count)))
            nxt += count
            sponge = sponge.absorb(elems)
        else:
            sponge, got = sponge.squeeze(count)
            out.extend(_to_canon(got))
    return out


_SCRIPTS = [(name, case) for name, case in _VECTORS["scripts"].items()]


class ArkDifferentialTest(parameterized.TestCase):
    """Both members against the release each one names."""

    @parameterized.named_parameters(*_SCRIPTS)
    def test_ark_0_3_matches_the_crate(self, case: dict) -> None:
        self.assertEqual(_run(ARK_0_3, case["steps"]), _expected(case["ark_0_3"]))

    @parameterized.named_parameters(*_SCRIPTS)
    def test_ark_0_5_matches_the_crate(self, case: dict) -> None:
        self.assertEqual(_run(ARK_0_5, case["steps"]), _expected(case["ark_0_5"]))

    @parameterized.named_parameters(*_SCRIPTS)
    def test_the_two_conventions_disagree(self, case: dict) -> None:
        # Every script differs, because `RateLanes` moves the rate to the other
        # end of the state and so changes every read — not only the scripts that
        # trip the spill skip. Asserted per script because a convention that
        # quietly collapsed onto the other would still pass both differentials
        # above if the vectors were ever regenerated from one implementation.
        self.assertTrue(case["differs"], "vector file says these agree")
        self.assertNotEqual(_run(ARK_0_3, case["steps"]), _run(ARK_0_5, case["steps"]))


class SpillPermuteSkipTest(absltest.TestCase):
    """The 0.3 bug itself, pinned as its own case.

    `squeeze(1)` leaves the read offset at 1; `squeeze(rate)` then outruns the
    block by exactly one. 0.3 tests the outstanding length against the rate
    *before* advancing its output slice, finds them equal, and skips the
    permute — so the second read comes off an unpermuted state and returns the
    lane the first squeeze already gave out.
    """

    _STEPS = [["squeeze", 1], ["squeeze", 2]]

    def test_ark_0_3_re_emits_the_first_lane(self) -> None:
        got = _run(ARK_0_3, self._STEPS)
        self.assertEqual(got[0], got[2], "0.3 must re-emit the already-squeezed lane")

    def test_ark_0_5_does_not_re_emit(self) -> None:
        got = _run(ARK_0_5, self._STEPS)
        self.assertEqual(len(set(got)), len(got), "0.5 permutes; no lane repeats")

    def test_the_quirk_case_fails_against_ark_0_5(self) -> None:
        # The acceptance criterion this row exists for: the skip is the thing
        # under test, so the case must distinguish the two conventions.
        self.assertNotEqual(_run(ARK_0_3, self._STEPS), _run(ARK_0_5, self._STEPS))

    def test_the_default_convention_does_not_re_emit(self) -> None:
        # `DEFAULT_CONVENTION` shares 0.3's rate layout, so it reads the same
        # lanes — and must still permute, which is what keeps the bug opt-in.
        got = _run(DEFAULT_CONVENTION, self._STEPS)
        self.assertEqual(len(set(got)), len(got))


class SwitchPermuteTest(absltest.TestCase):
    """The squeeze -> absorb switch, which only an interleaved script reaches.

    Every script that absorbs then squeezes and stops agrees on this axis, so it
    stayed invisible until the reference set grew one that turns back around —
    which is the argument for generating vectors from the crates rather than
    reasoning about which axes exist.
    """

    _STEPS = [["absorb", 2], ["squeeze", 1], ["absorb", 1], ["squeeze", 3]]

    def test_the_two_conventions_disagree_on_the_switch(self) -> None:
        # Isolated: same rate layout, same spill rule, only the switch differs.
        permuting = DuplexConvention(
            RateLanes.LEADING, SpillPermute.ALWAYS, SwitchPermute.BOTH_DIRECTIONS
        )
        skipping = DuplexConvention(
            RateLanes.LEADING,
            SpillPermute.ALWAYS,
            SwitchPermute.ABSORB_TO_SQUEEZE_ONLY,
        )
        self.assertNotEqual(_run(permuting, self._STEPS), _run(skipping, self._STEPS))

    def test_the_switch_is_invisible_without_a_reabsorb(self) -> None:
        # The reason this axis is easy to miss: with no squeeze -> absorb switch
        # the two settings are indistinguishable, so a reference set of
        # absorb-then-squeeze scripts would never have caught it.
        steps = [["absorb", 2], ["squeeze", 3]]
        permuting = DEFAULT_CONVENTION
        skipping = DuplexConvention(
            RateLanes.LEADING,
            SpillPermute.ALWAYS,
            SwitchPermute.ABSORB_TO_SQUEEZE_ONLY,
        )
        self.assertEqual(_run(permuting, steps), _run(skipping, steps))


class ConventionValueSurfaceTest(absltest.TestCase):
    """The members are values, not identities — a jit static arg needs that."""

    def test_equal_conventions_compare_and_hash_equal(self) -> None:
        rebuilt = DuplexConvention(
            rate_lanes=RateLanes.LEADING,
            spill_permute=SpillPermute.SKIP_WHEN_REQUEST_EQUALS_RATE,
            switch_permute=SwitchPermute.BOTH_DIRECTIONS,
        )
        self.assertEqual(rebuilt, ARK_0_3)
        self.assertEqual(hash(rebuilt), hash(ARK_0_3))

    def test_the_members_are_distinct(self) -> None:
        self.assertNotEqual(ARK_0_3, ARK_0_5)
        self.assertNotEqual(ARK_0_3, DEFAULT_CONVENTION)
        self.assertNotEqual(ARK_0_5, DEFAULT_CONVENTION)

    def test_each_axis_alone_distinguishes(self) -> None:
        # Both axes must be part of the value surface. A convention comparing
        # equal on one of them would serve one trace for the other's schedule —
        # the failure `byte_hash.Row` documents for the row seam.
        base = DEFAULT_CONVENTION
        self.assertNotEqual(
            base,
            DuplexConvention(
                RateLanes.TRAILING, base.spill_permute, base.switch_permute
            ),
        )
        self.assertNotEqual(
            base,
            DuplexConvention(
                base.rate_lanes,
                SpillPermute.SKIP_WHEN_REQUEST_EQUALS_RATE,
                base.switch_permute,
            ),
        )
        self.assertNotEqual(
            base,
            DuplexConvention(
                base.rate_lanes,
                base.spill_permute,
                SwitchPermute.ABSORB_TO_SQUEEZE_ONLY,
            ),
        )

    def test_a_convention_is_hashable_as_a_static_key(self) -> None:
        self.assertEqual(len({ARK_0_3, ARK_0_5, DEFAULT_CONVENTION}), 3)


class RateLanePlacementTest(absltest.TestCase):
    """The rate axis reaches absorb as well as squeeze."""

    def test_trailing_absorbs_into_the_high_lanes(self) -> None:
        width, rate = _VECTORS["width"], _VECTORS["rate"]
        x = fnp.asarray(list(range(1, rate + 1)), dtype=F)
        leading = DuplexSponge(_permutation(), rate=rate, convention=ARK_0_3).absorb(x)
        trailing = DuplexSponge(_permutation(), rate=rate, convention=ARK_0_5).absorb(x)
        lead_state = _to_canon(leading._state)
        trail_state = _to_canon(trailing._state)
        # Same values, opposite ends: capacity is the tail under LEADING and the
        # head under TRAILING.
        self.assertEqual(lead_state[:rate], trail_state[width - rate :])
        self.assertEqual(lead_state[width - 1], 0)
        self.assertEqual(trail_state[0], 0)


if __name__ == "__main__":
    absltest.main()
