load("@hash_frx_pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "rescue",
    srcs = [
        "__init__.py",
        "params.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        requirement("frx"),
        requirement("numpy"),
    ],
)
